---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: buildcache
  namespace: default
  labels:
    app: buildcache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
