---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: buildbuddy
  namespace: default
  labels:
    app: buildbuddy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
