apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-cert
  namespace: istio-system
spec:
  secretName: default-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - '*.build.resf.org'
    - 'build.resf.org'
    - '*.corp.build.resf.org'
